sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: groovy
jdk:
- openjdk8
- openjdk11
install: true
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: F9j8uujSJZm9VNO99PSSyV2knZgy0t8UOuJj6wrSLGnMqxmvp+hKkaC6uZgIP7c03/mxaZbEyUi608xgBYCrgkFdMoS3B2Q6/gOgB1E5QjsOFyKmhRc7mnd+7cSmNjNt1bAn///VaLgBkTo1aofoJnDahwWU8F7XtVEN4sbJ1w4=
  - secure: gRdx98zYWePrWQhjhXrrrpT0/70uAePJoNz3lKL/cL1luMi2QitC8+FiWWrkt7UqBGDnSmOK/HgCkBsaMjitvLN2/ctA/Xtuur06x+6g1dSd5HyM0nHOxb4CuUGomlbMp82L7AMiD9EjvdwjHrSHewMQhHvvNXfv2MeCiMAFn9g=
  - secure: YMx6w02GOup9FXItCrxNKLOw40Dd+gBykvT2NDw7La+EVgutRM7SkoG997jIzvJSS6sMKr8hJEcY0ygJFjVNGNBBAppXhvikBIYsadRhijn9vuWk2p1LthWYkEXX7HtTEJX6k2BKa7XaytATJTcL+xtafzkRZuGG27gYuNeYnY4=
  - secure: B9fzHVZ/tqkAvVPJqM1SKJAanIsPMT0gsUNHQQjAqPgLGMO9U5ob31vHC5d6wQ5keyHyrfe/XlhuEJJauQRnRNXoOX/DtFIZthJlHRc3zG8fILK+iXPi9t7GBoSzFWfZN9zf9/wnuy9vrU5TmMqNTHy4K2EuNlv1+LMNO2MQCwA=
  - secure: BOEEzbYp6u+wIOeO7jhg1vK4wCw9kxHIKRFrirsheFKswNFGU8LxKm9qZjCk2AuwpE0YVgadR4ujMqRFFAtwraDu+Q/rHdrugfqZxcXAuQF4jLFr2J0IskNZ2pODvEG+ybriL/S2rNlGX3yaoxJBPgN6egBtVXmieNlLNOAwZcg=
